apiVersion: v1
kind: ServiceAccount
metadata:
  name: healing-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: healing-operator
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status", "nodes", "services"]
    verbs: ["get", "list", "watch", "delete", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["healing.fyp.io"]
    resources: ["healingpolicies", "healingpolicies/status"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: healing-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: healing-operator
subjects:
  - kind: ServiceAccount
    name: healing-operator
    namespace: default
